# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63437bc334807703208e693a26bdacecf8e0c3fe0cafd441739b26fc5e2eba933be37a845caf2b585b823d4c566fe7437789a93f871f8277ec1135a27ae8bf50

test:
  secret_key_base: f05ba657ecd612001e1c67742c79b7fdbbc5ad25a2ed606d4abc142a1511aa6dce2e98aeaf3490e14304102a8e0d493fb7ed589f5ce31914f2d3aee8b658cc21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
